# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joanne Cheng
description: Personal site and portfolio of Joanne Cheng. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joannecheng.me" # the base hostname & protocol for your site
twitter_username: joannecheng
github_username: joannecheng

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
